-- MySQL Script generated by MySQL Workbench
-- Tue Jul 31 17:29:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie` DEFAULT CHARACTER SET utf8 ;
USE `movie` ;

-- -----------------------------------------------------
-- Table `movie`.`vip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie`.`vip` (
  `vip_id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`vip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie`.`movie` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `score` DECIMAL NOT NULL,
  `date` DATE NOT NULL,
  `introduce` TEXT NOT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`collect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie`.`collect` (
  `collect_id` INT NOT NULL AUTO_INCREMENT,
  `vip_id` INT NULL,
  `movie_id` INT NULL,
  PRIMARY KEY (`collect_id`),
  INDEX `vip_id_idx` (`vip_id` ASC),
  INDEX `movie_id_idx` (`movie_id` ASC),
  CONSTRAINT `collect_fk_vip`
    FOREIGN KEY (`vip_id`)
    REFERENCES `movie`.`vip` (`vip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `collect_fk_movie`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie`.`movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `vip_id` INT NULL,
  `movie_id` INT NULL,
  `comment` TEXT NULL,
  INDEX `id_vip_idx` (`vip_id` ASC),
  INDEX `id_movie_idx` (`movie_id` ASC),
  PRIMARY KEY (`comment_id`),
  CONSTRAINT `comment_fk_vip`
    FOREIGN KEY (`vip_id`)
    REFERENCES `movie`.`vip` (`vip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_fk_movie`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie`.`movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie`.`director` (
  `director_id` INT NOT NULL AUTO_INCREMENT,
  `director_name` VARCHAR(20) NULL,
  `director_sex` VARCHAR(5) NULL,
  `director_age` INT NULL,
  `director_country` VARCHAR(10) NULL,
  `director_desc` TEXT NULL,
  PRIMARY KEY (`director_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie`.`actor` (
  `actor_id` INT NOT NULL AUTO_INCREMENT,
  `actor_name` VARCHAR(20) NULL,
  `actor_sex` VARCHAR(5) NULL,
  `actor_age` INT NULL,
  `actor_country` VARCHAR(10) NULL,
  `actor_desc` TEXT NULL,
  PRIMARY KEY (`actor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`.`movieitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie`.`movieitem` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NULL,
  `actor_id` INT NULL,
  `director_id` INT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `movie_fk_movie_idx` (`movie_id` ASC),
  INDEX `movie_fk_director_idx` (`director_id` ASC),
  INDEX `movie_fk_actor_idx` (`actor_id` ASC),
  CONSTRAINT `movie_fk_movie`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie`.`movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_fk_director`
    FOREIGN KEY (`director_id`)
    REFERENCES `movie`.`director` (`director_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_fk_actor`
    FOREIGN KEY (`actor_id`)
    REFERENCES `movie`.`actor` (`actor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
